### ISSUE TITLE
Invalid SharedOptions in tests are blocking the co19 roll

### ISSUE THREAD

**Issue by athomas** [dart-lang/co19#1068]
There're too many `-` characters (3 instead of 2) in some shared options in tests:

https://github.com/dart-lang/co19/blob/0689ede15b16fde626b3086fcc861db07a290fb1/Language/Metadata/before_part_header_t01.dart#L12

This causes errors like this:
```
Exception: SharedOptions marker cannot mix experiment flags with other flags. Was:
---enable-experiment=generic-metadata
#0      new TestFile.parse (package:test_runner/src/test_file.dart:249:11)
#1      new TestFile.read (package:test_runner/src/test_file.dart:183:75)
#2      StandardTestSuite._processFile.sync_op (package:test_runner/src/test_suite.dart:664:29)
#3      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:181:26)
#4      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:198:26)
#5      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#6      new List.of (dart:core-patch/array_patch.dart:50:28)
#7      StandardTestSuite.findTestCases (package:test_runner/src/test_suite.dart:606:19)
#8      TestCaseEnqueuer.enqueueTestSuites (package:test_runner/src/process_queue.dart:239:13)
#9      new ProcessQueue (package:test_runner/src/process_queue.dart:177:22)
#10     testConfigurations (package:test_runner/src/test_configurations.dart:273:3)
#11     main (file:///Users/athom/src/sdk/pkg/test_runner/bin/test_runner.dart:44:9)
<asynchronous suspension>
```

@eernstg  @sgrekhov this is the issue behind the problem we discussed this morning.

**Comment by athomas** [comment]
This can be used to verify that all tests are fixed:
`tools/test.py -ndartk-weak-asserts-mac-release-x64 co19 --list`

**Comment by eernstg** [comment]
OK! I can see that the code in the test runner accepts the following:

```dart
// SharedOptions=--enable-experiment=generic-metadata,triple-shift,--no-hints
```

and this causes the analyzer to complain as follows:

```
> test_dartanalyzer language/scratch
Test configuration:
    analyzer-asserts-strong-linux(architecture: x64, compiler: dart2analyzer, mode: release, runtime: none, system: linux, nnbd: strong, enable-asserts, use-sdk)
Suites tested: language

FAILED: dart2analyzer-none release_x64 language/scratch_test
Expected: Pass
Actual: Crash

--- Command "dart2analyzer" (took 121ms):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dartanalyzer --enable-experiment=generic-metadata,triple-shift,--no-hints --ignore-unrecognized-flags --packages=/usr/local/google/home/eernst/devel/dart/work/sdk/.packages --format=machine --no-hints /usr/local/google/home/eernst/devel/dart/work/sdk/tests/language/scratch_test.dart

exit code:
253

stderr:
ERROR: Flag "--no-hints" not recognized.
Usage: dartanalyzer [options...] <directory or list of files>

    --dart-sdk                    The path to the Dart SDK.
    --options                     Path to an analysis options file.
    --[no-]declaration-casts      Disable declaration casts in strong mode (https://goo.gl/cTLz40)
                                  This option is now ignored and will be removed in a future release.
    --enable-experiment           Enable one or more experimental features. If multiple features are being added, they should be comma separated.
    --[no-]implicit-casts         Disable implicit casts in strong mode (https://goo.gl/cTLz40).
    --no-implicit-dynamic         Disable implicit dynamic (https://goo.gl/m0UgXD).
    --packages                    The path to the package resolution configuration file, which supplies a mapping of package names
                                  to paths.
    --[no-]lints                  Show lint results.
    --format                      Specifies the format in which errors are displayed; the only currently recognized values are 'json' and 'machine'.
    --version                     Print the analyzer version.
    --no-hints                    Do not show hint results.
...
```

That may not be optimal, but I guess we can't recommend any approach which is a lot better, so I haven't reported this.

**Comment by sgrekhov** [comment]
@athomas I fixed the issue and verified the tests. Thank you for pointing and sorry for the blocking typo. Please try to do the new roll

**Comment by athomas** [comment]
> ```dart
> // SharedOptions=--enable-experiment=generic-metadata,triple-shift,--no-hints
> ```

If we do need something like that in the future, we should have a space separating the list of experiments from other flags:
```dart
// SharedOptions=--enable-experiment=generic-metadata,triple-shift --no-hints
```
