### ISSUE TITLE
Isolate/spawn tests are failing due to closure sending restriction being lifted

### ISSUE THREAD

**Issue by aam** [dart-lang/co19#1190]
from [logs](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8837078416423714881/+/u/test_results/new_test_failures__logs_)

```
/=====================================================================================================================\
| dartk-strong-linux-debug-x64:co19/LibTest/isolate/Isolate/spawn_A02_t01 broke (Pass -> RuntimeError, expected Pass) |
\=====================================================================================================================/

--- Command "vm" (took 03.000101s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --sound-null-safety --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/tests/co19/src/LibTest/isolate/Isolate/spawn_A02_t01.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
Expect.fail(' a closure spawned: Instance of 'Isolate')')
#0      _fail (file:///b/s/w/ir/cache/builder/sdk/tests/co19/src/Utils/expect.dart:19:5)
#1      Expect.fail (file:///b/s/w/ir/cache/builder/sdk/tests/co19/src/Utils/expect_common.dart:81:5)
#2      main.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/tests/co19/src/LibTest/isolate/Isolate/spawn_A02_t01.dart:40:16)
<asynchronous suspension>
#3      main.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/tests/co19/src/LibTest/isolate/Isolate/spawn_A02_t01.dart)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dartk-strong-linux-debug-x64 co19/LibTest/isolate/Isolate/spawn_A02_t01


/=====================================================================================================================\
| dartk-strong-linux-debug-x64:co19/LibTest/isolate/Isolate/spawn_A02_t03 broke (Pass -> RuntimeError, expected Pass) |
\=====================================================================================================================/

--- Command "vm" (took 821ms):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --sound-null-safety --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19/src/LibTest/isolate/Isolate/spawn_A02_t03.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
Expect.fail('Isolate.spawn(new A().entryPoint, 'hello') is expected to fail')
#0      _fail (file:///b/s/w/ir/tests/co19/src/Utils/expect.dart:19:5)
#1      Expect.fail (file:///b/s/w/ir/tests/co19/src/Utils/expect_common.dart:81:5)
#2      main.<anonymous closure> (file:///b/s/w/ir/tests/co19/src/LibTest/isolate/Isolate/spawn_A02_t03.dart:37:14)
<asynchronous suspension>
#3      main.<anonymous closure> (file:///b/s/w/ir/tests/co19/src/LibTest/isolate/Isolate/spawn_A02_t03.dart)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dartk-strong-linux-debug-x64 co19/LibTest/isolate/Isolate/spawn_A02_t03


/===========================================================================================================================\
| dartk-weak-asserts-linux-debug-x64:co19/LibTest/isolate/Isolate/spawn_A02_t01 broke (Pass -> RuntimeError, expected Pass) |
\===========================================================================================================================/

--- Command "vm" (took 861ms):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --enable_asserts --no-sound-null-safety --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19/src/LibTest/isolate/Isolate/spawn_A02_t01.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
Expect.fail(' a closure spawned: Instance of 'Isolate')')
#0      _fail (file:///b/s/w/ir/tests/co19/src/Utils/expect.dart:19:5)
#1      Expect.fail (file:///b/s/w/ir/tests/co19/src/Utils/expect_common.dart:81:5)
#2      main.<anonymous closure> (file:///b/s/w/ir/tests/co19/src/LibTest/isolate/Isolate/spawn_A02_t01.dart:40:16)
<asynchronous suspension>
#3      main.<anonymous closure> (file:///b/s/w/ir/tests/co19/src/LibTest/isolate/Isolate/spawn_A02_t01.dart)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dartk-weak-asserts-linux-debug-x64 co19/LibTest/isolate/Isolate/spawn_A02_t01


/===========================================================================================================================\
| dartk-weak-asserts-linux-debug-x64:co19/LibTest/isolate/Isolate/spawn_A02_t03 broke (Pass -> RuntimeError, expected Pass) |
\===========================================================================================================================/

--- Command "vm" (took 01.000952s):
DART_CONFIGURATION=DebugX64 out/DebugX64/dart --enable_asserts --no-sound-null-safety --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19/src/LibTest/isolate/Isolate/spawn_A02_t03.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
Expect.fail('Isolate.spawn(new A().entryPoint, 'hello') is expected to fail')
#0      _fail (file:///b/s/w/ir/tests/co19/src/Utils/expect.dart:19:5)
#1      Expect.fail (file:///b/s/w/ir/tests/co19/src/Utils/expect_common.dart:81:5)
#2      main.<anonymous closure> (file:///b/s/w/ir/tests/co19/src/LibTest/isolate/Isolate/spawn_A02_t03.dart:37:14)
<asynchronous suspension>
#3      main.<anonymous closure> (file:///b/s/w/ir/tests/co19/src/LibTest/isolate/Isolate/spawn_A02_t03.dart)
<asynchronous suspension>

--- Re-run this test:
python3 tools/test.py -n dartk-weak-asserts-linux-debug-x64 co19/LibTest/isolate/Isolate/spawn_A02_t03
```

**Comment by sgrekhov** [comment]
@aam what change made these test failing? According to the [documentation](https://api.dart.dev/dev/2.15.0-82.0.dev/dart-isolate/Isolate/spawn.html)

> The entry-point function is invoked in the new isolate with message as the only argument.
> 
> The function must be a top-level function or a static method that can be called with a single argument, that is, a compile-time constant function value which accepts at least one positional parameter and has at most one required positional parameter.

These tests expect a runtime error if entry point is local function or instance method. If we are changing it then the documentation must be updated as well

**Comment by aam** [comment]
It was https://dart.googlesource.com/sdk/+/5f9ec9f52ac5788cdb0dc1bbde12b5298bd0cfd8

It's a good point about documentation! cc @mkustermann

**Comment by mkustermann** [comment]
> These tests expect a runtime error if entry point is local function or instance method. If we are changing it then the 
> documentation must be updated as well

There is still a flag - it's on-by-default but can be turned off. Once we remove the flag we can cleanup all the tests. Our Dart SDK tests run in both modes and check both behaviors but co19 can only check one behavior (the one for `--no-enable-isolate-groups`). We could update co19 tests now or when we remove the flag entirely.
