### ISSUE TITLE
Roll blocked because of bad syntax

### ISSUE THREAD

**Issue by athomas** [dart-lang/co19#1195]
https://dart-review.googlesource.com/c/sdk/+/213340
```
 FormatException: Invalid error expectation syntax in /b/s/w/ir/cache/builder/sdk/tests/co19/src/LanguageFeatures/Constructor-tear-offs/call_method_A05_t02.dart:
 FormatException: Test error on line 55: An analyzer error expectation should be a dotted identifier.
 #0      new TestFile.parse (package:test_runner/src/test_file.dart:317:7)
 #1      new TestFile.read (package:test_runner/src/test_file.dart:179:75)
 #2      StandardTestSuite._processFile (package:test_runner/src/test_suite.dart:682:29)
 #3      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:183:26)
 #4      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:198:26)
 #5      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
 #6      new List.of (dart:core-patch/array_patch.dart:50:28)
 #7      StandardTestSuite.findTestCases (package:test_runner/src/test_suite.dart:624:19)
 #8      TestCaseEnqueuer.enqueueTestSuites (package:test_runner/src/process_queue.dart:239:13)
 #9      new ProcessQueue (package:test_runner/src/process_queue.dart:177:22)
 #10     testConfigurations (package:test_runner/src/test_configurations.dart:273:3)
 #11     main (file:///b/s/w/ir/cache/builder/sdk/pkg/test_runner/bin/test_runner.dart:44:9)
 <asynchronous suspension>
```

**Comment by sgrekhov** [comment]
@athomas sorry for the typo. fixed. Please try again
