### ISSUE TITLE
LibTest/io/Link/rename_A02_t01 is flaky

### ISSUE THREAD

**Issue by mraleph** [dart-lang/co19#174]
Failed with 

```
FAILED: dartk-vm release_simdbc64 co19_2/LibTest/io/Link/rename_A02_t01
Expected: Pass
Actual: RuntimeError

--- Command "vm_compile_to_kernel" (took 623ms):
DART_CONFIGURATION=ReleaseSIMDBC64 /b/s/w/ir/pkg/vm/tool/gen_kernel --no-aot --platform=out/ReleaseSIMDBC64/vm_platform_strong.dill -o /b/s/w/ir/out/ReleaseSIMDBC64/generated_compilations/dartk/tests_co19_2_src_LibTest_io_Link_rename_A02_t01/out.dill /b/s/w/ir/tests/co19_2/src/LibTest/io/Link/rename_A02_t01.dart --packages=/b/s/w/ir/.packages -Ddart.developer.causal_async_stacks=true

exit code:
0

--- Command "vm" (took 445ms):
DART_CONFIGURATION=ReleaseSIMDBC64 out/ReleaseSIMDBC64/dart --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/ReleaseSIMDBC64/generated_compilations/dartk/tests_co19_2_src_LibTest_io_Link_rename_A02_t01/out.dill

exit code:
255

stderr:
Unhandled exception:
FileSystemException: Cannot create link, path = '/b/s/w/it9iDFpL/out_513-5454-9341-711.lnk' (OS Error: File exists, errno = 17)
#0      _Link.throwIfError (dart:io/link.dart:306:7)
#1      _Link.createSync (dart:io/link.dart:212:5)
#2      getTempLinkSync (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/file_utils.dart:57:8)
#3      main (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/Link/rename_A02_t01.dart:24:15)
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

--- Re-run this test:
python tools/test.py -m release -a simdbc64 -n dartk-linux-release-simdbc64 co19_2/LibTest/io/Link/rename_A02_t01
```

The underlying issue seems to be the code in `getTempLinkSync`

```dart
Link getTempLinkSync({Directory parent, String target, String name}) {
  parent ??= Directory.systemTemp;
  target ??= getTempDirectorySync(parent: parent).path;
  name ??= getPrefix() + getTempFileName(extension: ".lnk");
  Link link = new Link(parent.path + Platform.pathSeparator + name);
  link.createSync(target);
  return link;
}
```

Note that the link path is creating randomized name itself using `getTempFileName` - which can easily clash, because it does this:

```dart
String getTempFileName({String extension}) {
  if (rnd == null) {
    rnd = new Random(new DateTime.now().microsecondsSinceEpoch);
  }
  // ...
}
```

If two tests are reach this point the same time they can get exactly the same random seeds.

We recommend making sure that all temporary files are created within temporary directories created using `Directory.createTempSync` e.g. instead of doing 

```
parent ??= Directory.systemTemp;
```

you should create a temporary directory to serve as parent.

Of course it would be good if tests cleaned up after themselves too. 

Please audit all helpers used in File IO tests with this in mind.

**Comment by sgrekhov** [comment]
@mraleph I'm going to fix it in the following way. https://github.com/dart-lang/co19/pull/176
General idea is to use a separate sandbox for each test. Please review. If you agree with the approach I'll fix onthe tests in the same way

**Comment by a-siva** [comment]
Another case of failure which could be because of the same issue
```
DART_CONFIGURATION=ReleaseSIMDBC64 out/ReleaseSIMDBC64/dart --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/ReleaseSIMDBC64/generated_compilations/dartk/tests_co19_2_src_LibTest_io_FileSystemEntity_identicalSync_A02_t03/out.dill

exit code:
255

stderr:
Unhandled exception:
FileSystemException: Cannot create link, path = '/b/s/w/it9saX0o/out_9224-6474-4117-8932.lnk' (OS Error: File exists, errno = 17)
#0      _Link.throwIfError (dart:io/link.dart:308:7)
#1      _Link.createSync (dart:io/link.dart:214:5)
#2      getTempLinkSync (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/file_utils.dart:57:8)
#3      main (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemEntity/identicalSync_A02_t03.dart:29:15)
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

--- Re-run this test:
python tools/test.py -m release -a simdbc64 -n dartk-linux-release-simdbc64 co19_2/LibTest/io/FileSystemEntity/identicalSync_A02_t03
```

**Comment by sgrekhov** [comment]
Directory, Link and File tests rewritten to use a sandbox. 8a0216dcb3daa024a5b179490deba3f0b137c1da
