### ISSUE TITLE
LibTest/io/Stdin/readByteSync_A02_t01.dart is flaky

### ISSUE THREAD

**Issue by mraleph** [dart-lang/co19#175]
This test failed like this:

```
FAILED: dartk-vm release_x64 co19_2/LibTest/io/Stdin/readByteSync_A02_t01
Expected: Pass
Actual: RuntimeError

--- Command "vm" (took 02.000855s):
DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/cache/builder/sdk/.packages /b/s/w/ir/cache/builder/sdk/tests/co19_2/src/LibTest/io/Stdin/readByteSync_A02_t01.dart

exit code:
255

stderr:
Unhandled exception:
deepEquals([[53, 45, 49, 79, 75, 10]], [[53], [45, 49, 79, 75, 10]], ) fails
   [cause: Expect.equals(expected: <1>, actual: <2>, 'Collections' lengths are not equal: expected length=1, actual length=2') fails.]
#0      _fail (file:///b/s/w/ir/cache/builder/sdk/tests/co19_2/src/Utils/expect.dart:21:5)
#1      Expect.deepEquals (file:///b/s/w/ir/cache/builder/sdk/tests/co19_2/src/Utils/expect_common.dart:375:7)
#2      Expect.listEquals (file:///b/s/w/ir/cache/builder/sdk/tests/co19_2/src/Utils/expect_common.dart:303:5)
#3      run_main.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/tests/co19_2/src/LibTest/io/Stdin/readByteSync_A02_t01.dart:42:18)
#4      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#8      Future._complete (dart:async/future_impl.dart:476:7)
#9      Stream.toList.<anonymous closure> (dart:async/stream.dart:977:18)
#10     _RootZone.runGuarded (dart:async/zone.dart:1302:10)
#11     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#12     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#13     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#14     _SyncStreamController._sendDone (dart:async/stream_controller.dart:771:19)
#15     _StreamController._closeUnchecked (dart:async/stream_controller.dart:628:7)
#16     _StreamController.close (dart:async/stream_controller.dart:621:5)
#17     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1728:21)
#18     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#21     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#22     _StreamController._add (dart:async/stream_controller.dart:639:7)
#23     _StreamController.add (dart:async/stream_controller.dart:585:5)
#24     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1290:35)
#25     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:819:18)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

--- Re-run this test:
python tools/test.py -m release -n dartk-linux-release-x64 co19_2/LibTest/io/Stdin/readByteSync_A02_t01
```

The reason for the failure is that the test is not robust enough - it expects that we'll read all the bytes out from stdout in one go, which nobody guarantees.

The test should be made more robust by comparing flattened output. 

Please audit other tests for the same kind of issues.

**Comment by sgrekhov** [comment]
@mraleph, please review https://github.com/dart-lang/co19/pull/178

**Comment by sgrekhov** [comment]
Fixed by https://github.com/dart-lang/co19/pull/178
