### ISSUE TITLE
LibTest/io/FileSystemEntity/identical_A01_t06 is flaky

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/co19#183]
Looks like cleanup of the temporary directory is failing. Potentially related to #174?

```
FAILED: dartk-vm product_x64 co19_2/LibTest/io/FileSystemEntity/identical_A01_t06
Expected: Pass
Actual: RuntimeError

--- Command "vm" (took 746ms):
DART_CONFIGURATION=ProductX64 xcodebuild/ProductX64/dart --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19_2/src/LibTest/io/FileSystemEntity/identical_A01_t06.dart

exit code:
255

stdout:
unittest-suite-wait-for-done
unittest-suite-success

stderr:
Unhandled exception:
FileSystemException: Deletion failed, path = '/b/s/w/ir/3724-9690-6145-2802' (OS Error: No such file or directory, errno = 2)
#0      _Directory._delete.<anonymous closure> (dart:io/directory_impl.dart:198:9)
#1      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#4      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#5      Future._completeWithValue (dart:async/future_impl.dart:486:5)
#6      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#9      _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#10     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

--- Re-run this test:
python tools/test.py -m product -n dartk-mac-product-x64 co19_2/LibTest/io/FileSystemEntity/identical_A01_t06
```

**Comment by sgrekhov** [comment]
Fixed by https://github.com/dart-lang/co19/pull/189
