### ISSUE TITLE
LibTest/io/Stdin/first_A04_t01 should be made more robust

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/co19#193]
This test has the same issue as https://github.com/dart-lang/co19/issues/182: 

> Using `stdin.last.then(...)` in  `run_process()` is not right, since `stdin` is `Stream<List<int>>`, i.e. a stream of bytes. The bytes can be delivered in any sizes, e.g. each individual byte can be devlivered on it's own. So it cannot be assumed that the bytes obtained in `stdin.last` is  the last line.

Same for `stdin.first.then()` and `stdin.elementAt(0).then()`.

From [LibTest/io/Stdin/first_A04_t01.dart](https://github.com/dart-lang/co19/blob/master/LibTest/io/Stdin/first_A04_t01.dart):

```dart
run_process(String arg) {
  if(arg == "first") {
    stdin.first.then((List<int> l) {
      print(new String.fromCharCodes(l));
    });
  } else {
    stdin.elementAt(0).then((List<int> l) {
      print(new String.fromCharCodes(l));
    });
  }
}

run_main() async {
  String executable = Platform.resolvedExecutable;
  String eScript = Platform.script.toString();
  List<int> res_first, res_elementAt;

  await Process.start(executable, [eScript, "first"], runInShell: true).then(
      (Process process) async {
        process.stdin.writeln("12345");
        await process.stdout.toList().then((out) { res_first = out[0]; });
    });

  await Process.start(executable, [eScript, "elementAt"], runInShell: true).then(
      (Process process) async {
    process.stdin.writeln("12345");
    await process.stdout.toList().then((out) { res_elementAt = out[0]; });
  });

  Expect.listEquals(res_elementAt, res_first);
}
```

We see the following flakiness on our build infrastructure:

```dart
FAILED: dartk-vm release_simdbc64 co19_2/LibTest/io/Stdin/first_A04_t01
Expected: Pass
Actual: RuntimeError

--- Command "vm_compile_to_kernel" (took 535ms):
DART_CONFIGURATION=ReleaseSIMDBC64 /b/s/w/ir/pkg/vm/tool/gen_kernel --no-aot --platform=xcodebuild/ReleaseSIMDBC64/vm_platform_strong.dill -o /b/s/w/ir/xcodebuild/ReleaseSIMDBC64/generated_compilations/dartk/tests_co19_2_src_LibTest_io_Stdin_first_A04_t01/out.dill /b/s/w/ir/tests/co19_2/src/LibTest/io/Stdin/first_A04_t01.dart --packages=/b/s/w/ir/.packages -Ddart.developer.causal_async_stacks=true

exit code:
0

--- Command "vm" (took 01.000335s):
DART_CONFIGURATION=ReleaseSIMDBC64 xcodebuild/ReleaseSIMDBC64/dart --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/xcodebuild/ReleaseSIMDBC64/generated_compilations/dartk/tests_co19_2_src_LibTest_io_Stdin_first_A04_t01/out.dill

exit code:
255

stderr:
Unhandled exception:
deepEquals([49, 50, 51, 52, 53, 10, 10], [49, 50, 51, 52, 53, 10], ) fails
   [cause: Expect.equals(expected: <7>, actual: <6>, 'Collections' lengths are not equal: expected length=7, actual length=6') fails.]
#0      _fail (file:///b/s/w/ir/tests/co19_2/src/Utils/expect.dart:21:5)
#1      Expect.deepEquals (file:///b/s/w/ir/tests/co19_2/src/Utils/expect_common.dart:375:7)
#2      Expect.listEquals (file:///b/s/w/ir/tests/co19_2/src/Utils/expect_common.dart:303:5)
#3      run_main (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/Stdin/first_A04_t01.dart:46:10)
<asynchronous suspension>
#4      main (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/Stdin/first_A04_t01.dart:49:68)
#5      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

--- Re-run this test:
python tools/test.py -m release -a simdbc64 -n dartk-mac-release-simdbc64 co19_2/LibTest/io/Stdin/first_A04_t01
```

One of the two getting an extra newline byte (ascii `10`).

And prematurely closing sockets:

```dart
FAILED: dartk-vm release_simdbc64 co19_2/LibTest/io/Stdin/first_A04_t01
Expected: Pass
Actual: RuntimeError

--- Command "vm_compile_to_kernel" (took 606ms):
DART_CONFIGURATION=ReleaseSIMDBC64 /b/s/w/ir/pkg/vm/tool/gen_kernel --no-aot --platform=xcodebuild/ReleaseSIMDBC64/vm_platform_strong.dill -o /b/s/w/ir/xcodebuild/ReleaseSIMDBC64/generated_compilations/dartk/tests_co19_2_src_LibTest_io_Stdin_first_A04_t01/out.dill /b/s/w/ir/tests/co19_2/src/LibTest/io/Stdin/first_A04_t01.dart --packages=/b/s/w/ir/.packages -Ddart.developer.causal_async_stacks=true

exit code:
0

--- Command "vm" (took 850ms):
DART_CONFIGURATION=ReleaseSIMDBC64 xcodebuild/ReleaseSIMDBC64/dart --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/xcodebuild/ReleaseSIMDBC64/generated_compilations/dartk/tests_co19_2_src_LibTest_io_Stdin_first_A04_t01/out.dill

exit code:
255

stderr:
Unhandled exception:
SocketException: Write failed (OS Error: Broken pipe, errno = 32), port = 0
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#4      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

--- Re-run this test:
python tools/test.py -m release -a simdbc64 -n dartk-mac-release-simdbc64 co19_2/LibTest/io/Stdin/first_A04_t01
```

The socket was closed on the receiving end before the sending end had transmitted all bytes.

**Comment by iarkh** [comment]
Hello,

This problem is similar with the one described in the Issue #182. And unfortunately I am unable to reproduce both #182 and #193 in my environment.

If it's a test for checking stdin.first method and result line can be shorter than initial one, what should be an expected result of the test? Should I check that result string is the same as original and if this is not so -  it's a substring?

Regarding the following comment:

> One of the two getting an extra newline byte (ascii 10).

Is this a bug in the test or in SDK itself? Specification reads nothing regarding new line symbols here, so should I just trim them if they appear?

**Comment by lrhn** [comment]
The `stdin.writeln` will add a newline (it has "ln" at the end). The `print` in `run_process` will add another new-line. Whether you get both of them in the same message is apparently implementation dependent.

In either case, assuming that `out[0]` has any particular value is not warranted. It is the first chunk of the input, so all you know for certain is that it must be a prefix of what was written. Do not assume that it is the only chunk.

In this case, all input bytes will be ASCII characters, so using `String.fromCharCodes` should be safe, but again, you can only assume that it contains some number of leading characters.

I'd test this as:
```dart
run_main() async {
  ....  
  Expect.isTrue("12345\n\n".startsWith(String.fromCharCodes(res_first).replaceAll("\r\n", "\n")));
  Expect.isTrue("12345\n\n".startsWith(String.fromCharCodes(res_elementAt).replaceAll("\r\n", "\n")));
}
```
(I'm not assuming anything about newlines on Windows).

**Comment by iarkh** [comment]
FIXED
