### ISSUE TITLE
co19_2/LibTest/io/RawDatagramSocket/close_A01_t01 makes assumptions that UDP does not guarantee

### ISSUE THREAD

**Issue by mraleph** [dart-lang/co19#195]
The test has the following code

```dart
      receiver.listen((event) {
        received++;
        var datagram = receiver.receive();
        if (datagram != null) {
          Expect.equals(received - 1, datagram.data[0]);
        }
        if (timer2 != null) timer2.cancel();
        timer2 = new Timer(const Duration(milliseconds: 200), () {
          Expect.isNull(receiver.receive());
          receiver.close();
        });
      }).onDone(action);

```

It assumes that it will receive events in the same sequence as they were send. 

This is not an assumption that can be made with UDP as UDP does not provide ordering or even delivery guarantees.

**Comment by mraleph** [comment]
Test failed like so: 

```
FAILED: dartk-vm release_x64 co19_2/LibTest/io/RawDatagramSocket/close_A01_t01
Expected: Pass
Actual: RuntimeError

--- Command "vm" (took 400ms):
DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19_2/src/LibTest/io/RawDatagramSocket/close_A01_t01.dart

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
Expect.equals(expected: <2>, actual: <1>) fails.
#0      _fail (file:///b/s/w/ir/tests/co19_2/src/Utils/expect.dart:21:5)
#1      Expect.equals (file:///b/s/w/ir/tests/co19_2/src/Utils/expect_common.dart:30:5)
#2      check.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/RawDatagramSocket/close_A01_t01.dart:47:18)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#6      _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#7      _StreamController._add (dart:async/stream_controller.dart:640:7)
#8      _StreamController.add (dart:async/stream_controller.dart:586:5)
#9      new _RawDatagramSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1807:33)
#10     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

--- Re-run this test:
python tools/test.py -m release -n dartk-mac-release-x64 co19_2/LibTest/io/RawDatagramSocket/close_A01_t01
```

**Comment by sgrekhov** [comment]
@mraleph, @mkustermann,  this test is definitely wrong! It needs to be either rewritten it or removed. If we choose to rewrite (this and others RawDadagramSocket tests) we need to decide what can we assume. If tests should be based on the fact that UDP does not guarantee order and delivery, then we have almost nothing to test. Producer may send several datagrams, but if receiver even received no one of them it's OK. Then what to test? Do check that if receiver received anything then this data can be found among data sent by the producer? Whan about incomplete data then? If producer sent [1, 2, 3, 4] and [1, 2] were received? Is this an error or we should wait for another chunck of data, containing [3, 4]?

RawDatagramSocket.send() returns the number of bytes written. May we assume that if RawDatagramSocket.send() returned non zero, then these data should be received by receiver? If not, then, I guess, it's better simply to delete most of RawDatagramSocket tests.  Do you have any thoughts about this?

**Comment by dcharkes** [comment]
co19_2/LibTest/io/RawDatagramSocket/singleWhere_A03_t01 also assumes no packets are dropped.

```dart
      bcs.listen((event) {
        counter++;
        receiver.receive();
      }).onDone(() {
        Expect.equals(4, counter);
      });
```

```dart
FAILED: dartk-vm debug_simdbc64 co19_2/LibTest/io/RawDatagramSocket/singleWhere_A03_t01
Expected: Pass
Actual: RuntimeError

--- Command "vm_compile_to_kernel" (took 01.000214s):
DART_CONFIGURATION=DebugSIMDBC64 /b/s/w/ir/pkg/vm/tool/gen_kernel --no-aot --platform=out/DebugSIMDBC64/vm_platform_strong.dill -o /b/s/w/ir/out/DebugSIMDBC64/generated_compilations/dartk/tests_co19_2_src_LibTest_io_RawDatagramSocket_singleWhere_A03_t01/out.dill /b/s/w/ir/tests/co19_2/src/LibTest/io/RawDatagramSocket/singleWhere_A03_t01.dart --packages=/b/s/w/ir/.packages -Ddart.developer.causal_async_stacks=true

exit code:
0

--- Command "vm" (took 02.000696s):
DART_CONFIGURATION=DebugSIMDBC64 out/DebugSIMDBC64/dart --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/out/DebugSIMDBC64/generated_compilations/dartk/tests_co19_2_src_LibTest_io_RawDatagramSocket_singleWhere_A03_t01/out.dill

exit code:
255

stdout:
unittest-suite-wait-for-done

stderr:
Unhandled exception:
Expect.equals(expected: <4>, actual: <2>) fails.
#0      _fail (file:///b/s/w/ir/tests/co19_2/src/Utils/expect.dart:21:5)
#1      Expect.equals (file:///b/s/w/ir/tests/co19_2/src/Utils/expect_common.dart:30:5)
#2      check.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/tests/co19_2/src/LibTest/io/RawDatagramSocket/singleWhere_A03_t01.dart:58:16)
#3      _RootZone.runGuarded (dart:async/zone.dart:1302:10)
#4      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#5      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#6      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#7      _SyncBroadcastStreamController._sendDone.<anonymous closure> (dart:async/broadcast_stream_controller.dart:397:22)
#8      _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:324:15)
#9      _SyncBroadcastStreamController._sendDone (dart:async/broadcast_stream_controller.dart:396:7)
#10     _BroadcastStreamController.close (dart:async/broadcast_stream_controller.dart:272:5)
#11     _AsBroadcastStreamController.close (dart:async/broadcast_stream_controller.dart:498:27)
#12     _RootZone.runGuarded (dart:async/zone.dart:1302:10)
#13     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#14     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#15     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#16     _SyncStreamController._sendDone (dart:async/stream_controller.dart:772:19)
#17     _StreamController._closeUnchecked (dart:async/stream_controller.dart:629:7)
#18     _StreamController.close (dart:async/stream_controller.dart:622:5)
#19     new _RawDatagramSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1817:23)
#20     _NativeSocket.multiplex (dart:io/runtime/binsocket_patch.dart:899:39)
#21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

--- Re-run this test:
python tools/test.py -m debug -a simdbc64 -n dartk-linux-debug-simdbc64 co19_2/LibTest/io/RawDatagramSocket/singleWhere_A03_t01
```
