### ISSUE TITLE
LibTest/typed_data/Float32x4List/shuffle_A01_t02 is Flaky

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/co19#201]
From [this log](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8928595150547376912/+/steps/vm_co19_tests_shard_3/0/stdout):

```

FAILED: dartk-vm release_x64 co19_2/LibTest/typed_data/Float32x4List/shuffle_A01_t02
Expected: Pass
Actual: RuntimeError

--- Command "vm" (took 501ms):
DART_CONFIGURATION=ReleaseX64 xcodebuild/ReleaseX64/dart --sync-async --ignore-unrecognized-flags --packages=/b/s/w/ir/.packages /b/s/w/ir/tests/co19_2/src/LibTest/typed_data/Float32x4List/shuffle_A01_t02.dart

exit code:
255

stderr:
Unhandled exception:
Expect.isTrue(false) fails.
#0      _fail (file:///b/s/w/ir/tests/co19_2/src/Utils/expect.dart:21:5)
#1      Expect.isTrue (file:///b/s/w/ir/tests/co19_2/src/Utils/expect_common.dart:39:5)
#2      main (file:///b/s/w/ir/tests/co19_2/src/LibTest/typed_data/Float32x4List/shuffle_A01_t02.dart:55:10)
#3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

--- Re-run this test:
python tools/test.py -m release -n dartk-mac-release-x64 co19_2/LibTest/typed_data/Float32x4List/shuffle_A01_t02
```

If my math is correct than the current probability of this test failing is around 1 in 15000. Maybe we can change the `< 3` to `< 4`, which would lower the probability to around 1 in a million.

**Comment by mkustermann** [comment]
@sgrekhov Sounds also good!
