### ISSUE TITLE
LayoutTests/fast/xpath/invalid-resolver_t01 doesn't correctly catch checked exception

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/co19#21]
In checked mode, I get the following. It's inside a shouldThrow, but it seems to not catch the checked mode type error.

```
              value: test Expect.throws(resolver is a String) failed:Unexpected _TypeError('type 'String' is not a subtype of type 'XPathNSResolver' of 'resolver'.')
                    #0      XPathEvaluator.evaluate (dart:html:40552)
                    #1      main.<anonymous closure> (http://127.0.0.1:38432/root_dart/tests/co19/src/LayoutTests/fast/xpath/invalid-resolver_t01.dart:29:19)
                    #2      shouldThrow (http://127.0.0.1:38432/root_dart/tests/co19/src/LayoutTests/fast/xpath/xpath-test-pre.dart:91:11)
                    #3      main (http://127.0.0.1:38432/root_dart/tests/co19/src/LayoutTests/fast/xpath/invalid-resolver_t01.dart:28:5)
                    #4      main (http://127.0.0.1:38432/root_build/generated_tests/none-dartium-checked/tests_co19_src_LayoutTests_fast_xpath_invalid-resolver_t01/test.dart:5:3)
```

**Comment by sgrekhov** [comment]
Fixed. See 1662d5ce1bbbb930ea92c8f39f54b9d55c56eb8c and beeb4132fac776e00e237cf36d1e3a76c1119966
