### ISSUE TITLE
Test requirements are only supported for nnbd modes

### ISSUE THREAD

**Issue by athomas** [dart-lang/co19#536]
Currently, I can't roll co19 because of invalid Requirements annotations in tests:
```
 Unhandled exception:
 FormatException: Unknown feature "nnbd-strong,nonfunction-type-aliases" in test /b/s/w/ir/cache/builder/sdk/tests/co19/src/LanguageFeatures/nnbd/generics_A01_t03.dart
 #0      new TestFile.parse.<anonymous closure> (package:test_runner/src/test_file.dart:204:7)
 #1      _parseOption (package:test_runner/src/test_file.dart:39:26)
 #2      new TestFile.parse (package:test_runner/src/test_file.dart:199:9)
 #3      new TestFile.read (package:test_runner/src/test_file.dart:169:75)
 #4      StandardTestSuite._processFile (package:test_runner/src/test_suite.dart:536:29)
 #5      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:146:12)
 #6      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:139:32)
 #7      StandardTestSuite.findTestCases (package:test_runner/src/test_suite.dart:478:23)
 #8      TestCaseEnqueuer.enqueueTestSuites (package:test_runner/src/process_queue.dart:239:13)
 #9      new ProcessQueue (package:test_runner/src/process_queue.dart:177:22)
 #10     testConfigurations (package:test_runner/src/test_configurations.dart:252:3)
 #11     main (file:///b/s/w/ir/cache/builder/sdk/pkg/test_runner/bin/test_runner.dart:39:5)
 #12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
 #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
 INFO: No unexpected crashes recorded
```

https://github.com/dart-lang/co19/blob/bab998af42c215d347a5885d8e185c9b34f6f720/LanguageFeatures/nnbd/generics_A01_t03.dart#L18

The only supported values are:
nnbd
nnbd-legacy
nnbd-weak
nnbd-strong

**Comment by athomas** [comment]
To check that all tests are working, you can use:
```
$ tools/test.py --list co19
Test configuration:
    custom configuration(architecture: x64, compiler: dartk, mode: debug, runtime: vm, system: mac)
Suites tested: co19
Unhandled exception:
FormatException: Unknown feature "nnbd-strong,nonfunction-type-aliases" in test /Users/athom/src/sdk/tests/co19/src/LanguageFeatures/nnbd/generics_A01_t04.dart
#0      new TestFile.parse.<anonymous closure> (package:test_runner/src/test_file.dart:204:7)
#1      _parseOption (package:test_runner/src/test_file.dart:39:26)
#2      new TestFile.parse (package:test_runner/src/test_file.dart:199:9)
#3      new TestFile.read (package:test_runner/src/test_file.dart:169:75)
#4      StandardTestSuite._processFile (package:test_runner/src/test_suite.dart:536:29)
#5      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:146:12)
#6      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:139:32)
#7      StandardTestSuite.findTestCases (package:test_runner/src/test_suite.dart:478:23)
#8      TestCaseEnqueuer.enqueueTestSuites (package:test_runner/src/process_queue.dart:239:13)
#9      new ProcessQueue (package:test_runner/src/process_queue.dart:177:22)
#10     testConfigurations (package:test_runner/src/test_configurations.dart:252:3)
#11     main (file:///Users/athom/src/sdk/pkg/test_runner/bin/test_runner.dart:39:5)
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```
