### ISSUE TITLE
isolate-tests should not assume that 'main' is invoked synchronously.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/co19#75]
co19/LibTest/isolate/Isolate/spawn_A02_t04.dart and co19/LibTest/isolate/Isolate/spawn_A02_t05.dart need to be updated.

They assume that a bad entry-point can be caught by listening to the future of 'spawn', or that it can be caught by registering to the returned Future.

However, what happens is:
- in unchecked mode
- the isolate is successfully spawned, and an isolate is returned to the Future.
- asynchronously (in the new isolate) the given function is invoked with 1 argument, which leads to a runtime error.
- the isolate dies.
- the main isolate never sees the error in the second isolate (which makes the test fail).

What should be changed:
- since the other isolate fails, the spawning (main) isolate should register an error-handler to the 'spawn' process:

``` dart
  asyncStart();
  try {
    ReceivePort onError = new ReceivePort();
    var subscription;
    subscription = onError.listen((e) {
      Expect.isFalse(isCheckedMode);
      subscription.cancel();
      asyncEnd();
    });
    Isolate.spawn(entryPoint2Args, "hello", onError: onError.sendPort).then(
        (v) {
          Expect.isFalse(isCheckedMode);
        },
    );
  } catch (e) {
    print("Caught an error: $e");
    Expect.isTrue(isCheckedMode());
    asyncEnd();
  }
```

This code is only partially tested, but should give an idea of what should happen.

**Comment by whesse** [comment]
We have now seen a crash on the vm when running this test:
FAILED: none-vm release_x64 co19/LibTest/isolate/Isolate/spawn_A02_t05
Expected: RuntimeError 
Actual: Crash
CommandOutput[vm]:

stdout:
unittest-suite-wait-for-done


stderr:
Unhandled exception:
Expect.fail('Isolate.spawn(entryPointNoArgs, 'hello') is expected to fail')
#0      _fail (file:///b/build/slave/vm-mac-release-x64-be/build/sdk/tests/co19/src/Utils/expect.dart:17:5)
#1      Expect.fail (file:///b/build/slave/vm-mac-release-x64-be/build/sdk/tests/co19/src/Utils/expect_common.dart:79:5)
#2      main.<anonymous closure> (file:///b/build/slave/vm-mac-release-x64-be/build/sdk/tests/co19/src/LibTest/isolate/Isolate/spawn_A02_t05.dart:44:18)
#3      _RootZone.runUnary (dart:async/zone.dart:1404)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#7      _Future._complete (dart:async/future_impl.dart:467)
#8      _SyncCompleter.complete (dart:async/future_impl.dart:52)
#9      Isolate.spawn.<spawn_async_body> (dart:isolate-patch/isolate_patch.dart:334)
#10     _RootZone.runUnary (dart:async/zone.dart:1404)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#12     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#13     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#14     _Future._complete (dart:async/future_impl.dart:467)
#15     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#16     Isolate._spawnCommon.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:433)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
./vm/object.h: 5459: error: Handle check failed: saw UnwindError expected Instance
Dumping native stack trace for thread 1003
  [0x00000001100c9173] dart::Profiler::DumpStackTrace(bool)
  [0x00000001100c9173] dart::Profiler::DumpStackTrace(bool)
  [0x000000010fdc9d66] dart::DynamicAssertionHelper::Fail(char const*, ...)
  [0x000000010fecb879] dart::Instance::CheckedHandle(dart::RawObject*)
  [0x000000010fec04bb] dart::DRT_InlineCacheMissHandlerOneArg(dart::NativeArguments)
  [0x0000000111baa4c7] Unknown symbol
  [0x0000000111bab8b8] Unknown symbol
  [0x0000000112cbd893] Unknown symbol
  [0x0000000111baa982] Unknown symbol
  [0x000000010fee802f] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&)
  [0x000000010fee92a1] dart::DartEntry::InvokeNoSuchMethod(dart::Instance const&, dart::String const&, dart::Array const&, dart::Array const&)
  [0x000000010fec51fc] dart::DRT_InvokeClosureNoSuchMethod(dart::NativeArguments)
  [0x0000000111baa4c7] Unknown symbol
  [0x0000000111bacc2c] Unknown symbol
  [0x0000000112ca21cf] Unknown symbol
  [0x0000000112cbcaa2] Unknown symbol
  [0x0000000112ca21cf] Unknown symbol
  [0x0000000112cbc793] Unknown symbol
  [0x0000000111baa982] Unknown symbol
  [0x000000010fee802f] dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&)
  [0x000000010feeb4c3] dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)
  [0x000000010ffb274f] dart::IsolateMessageHandler::HandleMessage(dart::Message*)
  [0x000000010ffd9c26] dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
  [0x000000010ffda095] dart::MessageHandler::TaskCallback()
-- End of DumpStackTrace

**Comment by alsemenov** [comment]
The intention of the test is to check that spawning failure completes the spawning Future with error. The invalid entry point seems a good reason for a spawning failure. In other cases of invalid entry point (like null, string value, local function, method of a class) the error is returned through Future. For consistency reasons, I think in this case error also should be returned via Future.

**Comment by sgrekhov** [comment]
This is not an issue any longer in Dart 2.0. Closed
