### ISSUE TITLE
Two property extraction tests failing on dart2js

### ISSUE THREAD

**Issue by whesse** [dart-lang/co19#87]
Language/Expressions/Property_Extraction/Getter_Access_and_Method_Extraction/no_such_method_t01
Language/Expressions/Property_Extraction/Super_Getter_Access_and_Method_Closurization/no_such_method_t01

These two tests are failing on all dart2js platforms, with the error:
 type: sync_exception
              value: Exception: Expect.equals(expected: <{}>, actual: <{}>) fails.
                    Stack: Expect.equals(expected: <{}>, actual: <{}>) fails.
                        at Object.wrapException (http://127.0.0.1:38915/root_build/generated_compilations/dart2js-sdk/tests_co19_src_Language_Expressions_Property_Extraction_Super_Getter_Access_and_Method_Closurization_no_such_method_t01/test.js:846:17)
                        at Object._fail (http://127.0.0.1:38915/root_build/generated_compilations/dart2js-sdk/tests_co19_src_Language_Expressions_Property_Extraction_Super_Getter_Access_and_Method_Closurization_no_such_method_t01/test.js:1999:15)
                        at Object.Expect_equals (http://127.0.0.1:38915/root_build/generated_compilations/dart2js-sdk/tests_co19_src_Language_Expressions_Property_Extraction_Super_Getter_Access_and_Method_Closurization_no_such_method_t01/test.js:2004:9)
                        at C.dart.A.noSuchMethod$1 (http://127.0.0.1:38915/root_build/generated_compilations/dart2js-sdk/tests_co19_src_Language_Expressions_Property_Extraction_Super_Getter_Access_and_Method_Closurization_no_such_method_t01/test.js:2031:11)
                        at main (http://127.0.0.1:38915/root_build/generated_compilations/dart2js-sdk/tests_co19_src_Language_Expressions_Property_Extraction_Super_Getter_Access_and_Method_Closurization_no_such_method_t01/test.js:2021:9)
                        at dartMainRunner (http://127.0.0.1:38915/root_dart/tools/testing/dart/test_controller.js:311:5)
                        at http://127.0.0.1:38915/root_build/generated_compilations/dart2js-sdk/tests_co19_src_Language_Expressions_Property_Extraction_Super_Getter_Access_and_Method_Closurization_no_such_method_t01/test.js:2303:7
                        at init.currentScript (http://127.0.0.1:38915/root_build/generated_compilations/dart2js-sdk/tests_co19_src_Language_Expressions_Property_Extraction_Super_Getter_Access_and_Method_Closurization_no_such_method_t01/test.js:2289:7)
                        at http://127.0.0.1:38915/root_build/generated_compilations/dart2js-sdk/tests_co19_src_Language_Expressions_Property_Extraction_Super_Getter_Access_and_Method_Closurization_no_such_method_t01/test.js:2300:5
                        at http://127.0.0.1:38915/root_build/generated_compilations/dart2js-sdk/tests_co19_src_Language_Expressions_Property_Extraction_Super_Getter_Access_and_Method_Closurization_no_such_method_t01/test.js:2308:3
              timestamp: 0.041

**Comment by sgrekhov** [comment]
Tests are ok. I believe that this is not co19 issue, but dart2js bug. These two tests are faining because of https://github.com/dart-lang/sdk/issues/24331. Seems that it was fixed in VM but still not fixed in dart2js.
@whesse please update .status files, add # Issue 24331
