### ISSUE TITLE
HTTP 308 tests need to be added

### ISSUE THREAD

**Issue by filiph** [dart-lang/co19#944]
I just made a change to support HTTP 308 redirects: https://dart-review.googlesource.com/c/sdk/+/165404.

Tests like `co19/src/LibTest/io/HttpClientResponse/redirects_A01_t02.dart` need to be updated with something like:

```dart
// ... top of file elided ...

main() {
  test("get", HttpStatus.movedPermanently);
  test("get", HttpStatus.found);
  test("get", HttpStatus.movedTemporarily);
  test("get", HttpStatus.seeOther);
  test("get", HttpStatus.temporaryRedirect);
  test("get", HttpStatus.permanentRedirect);   // <--- adding this

  test("head", HttpStatus.movedPermanently);
  test("head", HttpStatus.found);
  test("head", HttpStatus.movedTemporarily);
  test("head", HttpStatus.seeOther);
  test("head", HttpStatus.temporaryRedirect);
  test("head", HttpStatus.permanentRedirect);   // <---- and this
}
```

Basically, anywhere there's `HttpStatus.movedPermanently` (HTTP 301) in a list like this, there should also be `HttpStatus.permanentRedirect` (HTTP 308) added.

**Comment by sgrekhov** [comment]
@filiph I tried to update https://github.com/dart-lang/co19/blob/master/LibTest/io/HttpClientResponse/redirects_A01_t02.dart as you suggested but got an error

```
unittest-suite-wait-for-done
Unhandled exception:
Expect.equals(expected: <1>, actual: <0>) fails.
#0      _fail (file:///D:/work/Google/co19/Utils/expect.dart:20:5)
#1      Expect.equals (file:///D:/work/Google/co19/Utils/expect_common.dart:30:5)
#2      test.<anonymous closure> (file:///D:/work/Google/co19/LibTest/io/HttpClientResponse/redirects_A01_t02.dart:49:12)
#3      _RootZone.runUnary (dart:async/zone.dart:1450:54)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#8      Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
#9      _RootZone.runUnary (dart:async/zone.dart:1450:54)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#14     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

Process finished with exit code 255
```
I also tried to add `test("get", HttpStatus.permanentRedirect);` to https://github.com/dart-lang/co19/blob/master/LibTest/io/HttpClientRequest/followRedirects_A02_t01.dart and test timeouts. What should be changed to make these tests working? Or, may be, this is an issue?

I use `Dart SDK version: 2.11.0-180.0.dev (dev) (Tue Sep 29 19:40:19 2020 -0700) on "windows_x64"`

**Comment by filiph** [comment]
Hm, I wonder if the change is already in the `dev` channel. It landed to `master` literally yesterday.

**Comment by sgrekhov** [comment]
@filiph that means that there is no the change in SDK version form Sept 29 :) I'll retest on the edge version. Thank you
